---

# Playbook wth logic

- hosts: web:db
  #sudo: yes
  become: yes
  vars:
    doc_root: "/var/www/html/mywebappv2"
    username: "Amit"
  tasks:
  - name: Install Apache Packages 
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"
    

  - name: Install HTTPD Packages 
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start HTTPD Service
    service: name=httpd state=started enabled=True
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service
    service: name=apache2 state=started enabled=True
    when: ansible_os_family == "Debian"

  - name: Purge the old Dir
    file: path=/var/www/html/ state=absent

  - name: Create Site Location
    file: path={{doc_root}} state=directory mode=0755

  - name: Deploy DB ConfigFile
    copy: src=files/index-db.html dest={{doc_root}}/info-db.html

  - name: Common Custom Web Page
    copy: src=files/common.html dest={{doc_root}}/common.html
  
  - name: Check the Web file
    command: ls {{doc_root}}/info.html
    register: result1
    ignore_errors: yes

  - debug: msg="Unable to locate file info.html"
    when: result1|failed


  - debug: msg="The file has been located file info.html"
    when: result1|success

  - debug: msg="What are you holding in-{{result1}}"

  - name: Web Page
    copy: src=files/info.html dest={{doc_root}}/info.html
    when: result1|failed


  - name: Template Web Page
    template: src=templates/sample.j2 dest={{doc_root}}/sample.html

  - name: Template Web Page
    template: src=templates/info.j2 dest={{doc_root}}/info-2.html
