---
# handlers file for webserver
- name: Restart Apache
  service: name=apache2 state=restarted
  
- name: amit
  shell: 'echo "Hello Handlers {{ansible_hostname}}" >> /tmp/abc.txt'
  delegate_to: 127.0.0.1
