---

- hosts: 'web:db'
  become: yes
  vars:
    change_id: CH00004321
  pre_tasks:
  - include: roles/pre-and-post-tasks/tasks/pre-task.yaml 
  roles:
  - firewalld
  - webserver
  - server-common
  post_tasks:
  - include: roles/pre-and-post-tasks/tasks/post-task.yaml 
