ec2:
  region: ap-south-1
  credentials: my-aws-ssh-key
  image: ami-04c342a3b8070ffa1 
  instance_type: t2.micro 
  sg: ansiblewinSG
  subnet: subnet-e18f1489
  public_ip: yes
  user_data: user_data/winrm.txt
  count: 1
  tags:
    Name: Win_Ansible
