---

- hosts: 'web'
  become: yes
  name: "Server Common Tasks"
  vars:
    manala_motd_template: template/dragon.j2
    manala_motd_message:  Hey Dragon.!!
  roles:
  - firewalld
  - server-common
  - motd
  - local-remote-actions
