---

# Playbook wth logic

- hosts: web:db
  #sudo: yes
  become: yes
  tasks:
  - name: Install Apache Packages 
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"
    

  - name: Install HTTPD Packages 
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start HTTPD Service
    service: name=httpd state=started enabled=True
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service
    service: name=apache2 state=started enabled=True
    when: ansible_os_family == "Debian"

  - name: Deploy DB ConfigFile
    copy: src=files/index-db.html dest=/var/www/html/info-db.html

  - name: Common Custom Web Page
    copy: src=files/common.html dest=/var/www/html/common.html
  
  - name: Check the Web file
    command: ls /var/www/html/info.html
    register: result1
    ignore_errors: yes

  - debug: msg="Unable to locate file info.html"
    when: result1|failed


  - debug: msg="The file has been located file info.html"
    when: result1|success

  - debug: msg="What are you holding in-{{result1}}"

  - name: Web Page
    copy: src=files/info.html dest=/var/www/html/info.html
    when: result1|failed
